[project]
name = "frontend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-core>=1.0.2",
    "langchain-openai>=1.0.1",
    "pydantic>=2.12.3",
    "pyqt6>=6.10.0",
    "pyside6>=6.10.0",
]
